# Generated by Django 2.1.7 on 2024-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('subtopic', models.CharField(default='not required', max_length=30)),
                ('expertise', models.CharField(max_length=30)),
                ('number', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Interview_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=30)),
                ('subtopic', models.CharField(default='not required', max_length=30)),
                ('expertise', models.CharField(default='', max_length=30)),
                ('number', models.IntegerField(default=10)),
                ('up', models.IntegerField(default=0)),
                ('happy', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('surprise', models.IntegerField(default=0)),
                ('max_emotions', models.IntegerField(default=0)),
                ('feedback', models.TextField(default='ans')),
                ('ec_center', models.CharField(default='ans', max_length=255)),
                ('loc1', models.BooleanField(default=True)),
                ('loc2', models.BooleanField(default=True)),
                ('questions', models.TextField(default='ans')),
                ('answers', models.TextField(default='ans')),
                ('answers_feedback', models.TextField(default='ans_feed')),
                ('indices', models.TextField(default='ans')),
                ('num', models.IntegerField(default=0)),
            ],
        ),
    ]
