# Generated by Django 2.1.7 on 2023-10-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('subtopic', models.CharField(default='not required', max_length=30)),
                ('expertise', models.CharField(max_length=30)),
                ('number', models.IntegerField(default=10)),
            ],
        ),
    ]
