# Generated by Django 2.1.7 on 2023-10-30 13:36

from django.db import migrations, models
import gridfs_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pic', models.ImageField(storage=gridfs_storage.storage.GridFSStorage(location='C:\\Users\\saini\\OneDrive\\Desktop\\Major Project\\MockMentor\\static\\images\\interview.png'), upload_to='')),
            ],
        ),
    ]
