# Generated by Django 2.1.7 on 2024-01-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_feedback',
            name='email',
            field=models.CharField(default='sai@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='interview_feedback',
            name='ec_center',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interview_feedback',
            name='max_emotions',
            field=models.TextField(default='ans'),
        ),
    ]
