# Generated by Django 4.1.13 on 2024-01-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interview_feedback',
            name='ec_center',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interview_feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interview_feedback',
            name='max_emotions',
            field=models.TextField(default='ans'),
        ),
    ]
