# Generated by Django 2.1.7 on 2023-10-30 13:38

from django.db import migrations, models
import gridfs_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='first_pic',
            field=models.ImageField(storage=gridfs_storage.storage.GridFSStorage(location='sample/images'), upload_to=''),
        ),
    ]
