# Generated by Django 2.1.7 on 2024-01-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20231030_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
